apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/marcusdunn/self-hosted
    path: root
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
