apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-admin
  namespace: pihole
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-admin
                port:
                  number: 80
