apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pihole
  namespace: pihole
resources:
  - namespace.yaml
  - deployment.yaml
  - dns-service.yaml
  - admin-service.yaml
  - ingress.yaml